version: '3.8'

services:

  web:
    build: ./app
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:8.0.36
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

networks:
  backend:

volumes:
  mysql_data: